sudo: false
# language: node_js
# node_js:
#   - 10 # use nodejs v10 LTS
# cache: npm
# branches:
#   only:
#     - master # build master branch only
# script:
#   - hexo generate # generate static files
# deploy:
#   provider: pages
#   skip-cleanup: true
#   github-token: $GH_TOKEN
#   keep-history: true
#   on:
#     branch: master
#   local-dir: public
language: node_js

node_js: stable

cache:
  directories:
  - node_modules
before_install:
  - npm install -g hexo-cli

install:
  - npm install

script:
  - hexo g 

after_script:
  - cd ./public
  - git init
  - git config user.name "geneningz"
  - git config user.email "zhangjlin5@qq.com"
  - git add .
  - git commit -m "TravisCI 自动部署"
  # Github Pages
  - git push --force --quiet "https://${
    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}@${
    GH_REF}" master:master

env:
  global:
    - GH_REF: github.com/Genening/Genening.github.io.git
  
notifications:
  email:
    - zhangjlin5@qq.com
  on_success: change
  on_failure: always
